Feature/authenticate
virto-network/frame-contrib pull request #20
Opened 2024-06-17 21:33 UTC by johandroid

2024-06-17 21:34 UTC, jgutierrezre reviewed
lgtm

2024-06-17 21:35 UTC, jgutierrezre approved these changes
lgtm

2024-06-22 04:04 UTC, pandres95 requested changes
Overall is good. Just consider we need to use `Randomness` on every step we attempt an authentication.

2024-06-22 04:04 UTC, pandres95 commented on pallets/pass/src/lib.rs
> +                    &block_number_mod_x_bytes[..],
Use the `T::Randomness` to preserve consistency across methods

2024-06-22 15:22 UTC, pandres95 approved these changes

2024-06-22 15:22 UTC, merged