feat(fc-pallet-pass): add `SkipCheckIfPassAccount`
virto-network/frame-contrib pull request #28
Opened 2024-11-19 02:47 UTC by pandres95

This new extension skips certain checks (like `CheckNonce`) if the caller is a session key.

This extension should be deprecated in the future in favour of a couple of `TransactionExtension`s
that:

1. Issues a new custom origin from `pallet-pass` to wrap the account and skip checks. Then,
2. After those checks, replaces this custom origin with [`frame_system::RawOrigin::Signed`],
   where the signed `account_id` is the derived `AccountId` associated to the account handled by
   `pallet-pass`.

2024-11-21 07:14 UTC, jgutierrezre approved these changes
lgtm

2024-11-21 15:11 UTC, olanod requested changes
Let's use the scheduler to auto remove sessions based on their expiration block and extend the removal schedule when necessary.

Side note based on our talk, in a different PR let's improve our account generation in `account_id_for` which currently trusts user provided data when it shouldn't. I propose something like
```
// we know the length of HashedUserId
let mut input = [0u8; TWICE_THE_LEN_OF_HASHED_USER_ID];
input[..HASHED_USER_ID_LEN] = input.copy_from_slice(&user);
let account = hash_input_and_magically_convert_to_account(&input);
```

2024-11-21 16:10 UTC, pandres95 commented on pallets/pass/src/lib.rs
> +    }
```suggestion
    fn do_remove_session(who: &T::AccountId) {
        // Decrements the provider reference of this `Session` key account once it's expired.
        //
        // NOTE: This might not get called at all. We should explore an alternative (maybe a
        // task) to remove the provider references on all expired sessions.
        let _ = frame_system::Pallet::<T>::dec_providers(who).inspect_err(|e| log::warn!("Failed to remove the last provider for {who:?}, which has an active consumer"));
        Sessions::<T, I>::remove(who);
    }
```

2024-11-22 11:21 UTC, olanod approved these changes
LGTM :)

2024-11-22 11:21 UTC, merged